oe_corporate_blocks.footer.links:
  type: sequence
  label: 'A list of footer links'
  sequence:
    type: oe_corporate_blocks.footer.link

oe_corporate_blocks.footer.link:
  type: mapping
  label: 'Footer link'
  mapping:
    external:
      type: boolean
      label: 'Is external link.'
    href:
      type: string
      label: 'Link URL'
      translatable: true
    label:
      type: string
      label: 'The link label'
      translatable: true

oe_corporate_blocks.ec_data.footer:
  type: config_object
  label: 'Data for EC corporate bocks.'
  mapping:
    corporate_site_link:
      type: oe_corporate_blocks.footer.link
    class_navigation:
      type: oe_corporate_blocks.footer.links
    service_navigation:
      type: oe_corporate_blocks.footer.links
    legal_navigation:
      type: oe_corporate_blocks.footer.links

oe_corporate_blocks.eu_data.footer:
  type: config_object
  label: 'Data for EU corporate bocks.'
  mapping:
    contact_title:
      type: string
      label: 'Title of contact column'
      translatable: true
    contact:
      type: sequence
      label: 'Contact information'
      sequence:
        type: oe_corporate_blocks.footer.link
    social_media_title:
      type: string
      label: 'Title of social media column'
      translatable: true
    social_media:
      type: sequence
      label: 'EU social media'
      sequence:
        type: oe_corporate_blocks.footer.link
    institution_links_title:
      type: string
      label: 'Title of institution links column'
      translatable: true
    institution_links:
      type: sequence
      label: 'EU institution links'
      sequence:
        type: oe_corporate_blocks.footer.link
    legal_links_title:
      type: string
      label: 'Title of legal links column'
    legal_links:
      type: sequence
      label: 'Legal links'
      sequence:
        type: oe_corporate_blocks.footer.link

oe_corporate_blocks.footer_link.general.*:
  type: config_entity
  label: 'General link for site specific footer'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: string
      label: 'URL'
      translatable: true
      form_element_class: '\Drupal\config_translation\FormElement\Textfield'
    section:
      type: string
      label: 'Section'
    weight:
      type: integer
      label: 'Weight'

oe_corporate_blocks.footer_link.social.*:
  type: oe_corporate_blocks.footer_link.general.*
  label: 'Social link for site specific footer'
  mapping:
    social_network:
      type: string
      label: 'Social network'

oe_corporate_blocks.footer_link.section.*:
  type: config_entity
  label: 'Section for site specific footer links'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
