oe_corporate_blocks.ec_data.footer:
  type: config_object
  label: 'Data for EC corporate bocks.'
  mapping:
    about_ec_title:
      type: string
      label: 'About EC title'
      translatable: true
    about_ec_links:
      type: oe_corporate_blocks.footer.links
    social_media_title:
      type: string
      label: 'Social media title'
      translatable: true
    social_media_links:
      type: sequence
      label: 'Social media links'
      sequence:
        type: mapping
        label: 'Social media link data'
        mapping:
          type:
            type: string
            label: 'The type of the social media link'
          icon:
            type: string
            label: 'The icon of the social media link'
          link:
            type: oe_corporate_blocks.footer.link
    about_eu_title:
      type: string
      label: 'About EU title'
      translatable: true
    about_eu_links:
      type: oe_corporate_blocks.footer.links
    bottom_links:
      type: oe_corporate_blocks.footer.links

oe_corporate_blocks.footer.links:
  type: sequence
  label: 'A list of footer links'
  sequence:
    type: oe_corporate_blocks.footer.link

oe_corporate_blocks.footer.link:
  type: mapping
  label: 'Footer link'
  mapping:
    href:
      type: string
      label: 'Link URL'
      translatable: true
    label:
      type: string
      label: 'The link label'
      translatable: true

oe_corporate_blocks.eu_data.footer:
  type: config_object
  label: 'Data for EU corporate bocks.'
  mapping:
    contact_title:
      type: string
      label: 'Title of contact column'
      translatable: true
    contact:
      type: sequence
      label: 'Contact information'
      sequence:
        translatable: true
        type: string
    social_media_title:
      type: string
      label: 'Title of social media column'
      translatable: true
    social_media:
      type: sequence
      label: 'EU social media'
      sequence:
        type: oe_corporate_blocks.footer.link
    institution_links_title:
      type: string
      label: 'Title of institution links column'
      translatable: true
    institution_links:
      type: sequence
      label: 'EU institution links'
      sequence:
        type: oe_corporate_blocks.footer.link
    other_links:
      type: sequence
      label: 'EU other links'
      sequence:
        type: oe_corporate_blocks.footer.link

oe_corporate_blocks.footer_link.general.*:
  type: config_entity
  label: 'General link for custom footer'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    url:
      type: string
      label: 'URL'
      translatable: true
      form_element_class: '\Drupal\config_translation\FormElement\Textfield'
    weight:
      type: integer
      label: 'Weight'

oe_corporate_blocks.footer_link.social.*:
  type: oe_corporate_blocks.footer_link.general.*
  label: 'Social link for custom footer'
  mapping:
    social_network:
      type: string
      label: 'Social network'
