oe_corporate_blocks.data.footer:
  type: config_object
  label: 'Data for corporate bocks.'
  mapping:
    about_ec_title:
      type: string
      label: 'About EC title'
      translatable: true
    about_ec_links:
      type: oe_corporate_blocks.footer.links
    social_media_title:
      type: string
      label: 'Social media title'
      translatable: true
    social_media_links:
      type: sequence
      label: 'Social media links'
      sequence:
        type: mapping
        label: 'Social media link data'
        mapping:
          type:
            type: string
            label: 'The type of the social media link'
          icon:
            type: string
            label: 'The icon of the social media link'
          link:
            type: oe_corporate_blocks.footer.link
    about_eu_title:
      type: string
      label: 'About EU title'
      translatable: true
    about_eu_links:
      type: oe_corporate_blocks.footer.links
    bottom_links:
      type: oe_corporate_blocks.footer.links

oe_corporate_blocks.footer.links:
  type: sequence
  label: 'A list of footer links'
  sequence:
    type: oe_corporate_blocks.footer.link

oe_corporate_blocks.footer.link:
  type: mapping
  label: 'Footer link'
  mapping:
    href:
      type: string
      label: 'Link URL'
      translatable: true
    label:
      type: string
      label: 'The link label'
      translatable: true

oe_corporate_blocks.data.site_switcher:
  type: config_object
  label: 'Data for site switcher bock.'
  mapping:
    info_label:
      type: string
      label: 'Info site link label'
      translatable: true
    info_url:
      type: string
      label: 'Info site link URL'
      translatable: true
    political_label:
      type: string
      label: 'Political site link label'
      translatable: true
    political_url:
      type: string
      label: 'Political site link URL'
      translatable: true
    active:
      type: string
      label: 'Active link'
